# Generated by Django 5.2 on 2026-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0025_pushed_authorization_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='backchannel_logout_uri',
            field=models.URLField(
                blank=True,
                help_text="Backchannel Logout URI where logout tokens will be sent",
                null=True,
                verbose_name="backchannel logout URI",
            ),
        ),
    ]
